DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;


CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM	DATE,
	STRASSE         VARCHAR(50),
	HAUSNR			VARCHAR(6),			
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    BUNDESLAND		VARCHAR(50),
    PRIMARY KEY (KUNDENNR)
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR			VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON			VARCHAR(25),
    EMAIL           VARCHAR(50),
    BUNDESLAND		VARCHAR(50),
    PRIMARY KEY (LIEFERANTENNR)
);

CREATE TABLE NÄHRWERTE (
	NÄHRWERTE_ID	INTEGER,
	KALORIEN		FLOAT,
    KOHLENHYDRATE	FLOAT,
    PROTEINE		FLOAT,
    BALLASTSTOFFE	FLOAT,
    FETT			FLOAT,
    NATRIUM			FLOAT,
    PRIMARY KEY (NÄHRWERTE_ID)
);

CREATE TABLE ZUTAT(
    ZUTAT_ID			INTEGER NOT NULL,
    BEZEICHNUNG         VARCHAR(50),
    EINHEIT        		VARCHAR (25),
    NETTOPREIS       	DECIMAL(10,2),
    BESTAND             INTEGER,
    LIEFERANT			INTEGER,
    NÄHRWERTE_ID		INTEGER,
	PRIMARY KEY (ZUTAT_ID),
	FOREIGN KEY (NÄHRWERTE_ID) REFERENCES NÄHRWERTE (NÄHRWERTE_ID),
	FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR)
);

CREATE TABLE BESTELLUNG (
    BESTELLNR        INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENNR         INTEGER,
    BESTELLDATUM     DATE,
    RECHNUNGSBETRAG  DECIMAL(10,2),
    PRIMARY KEY (BESTELLNR),
    FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR)
);

CREATE TABLE BESTELLUNGZUTAT (
    BESTELLNR       INTEGER NOT NULL,
    ZUTAT_ID      INTEGER,
    MENGE     		INTEGER,
    PRIMARY KEY (BESTELLNR,ZUTAT_ID),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (ZUTAT_ID) REFERENCES ZUTAT (ZUTAT_ID)
);

CREATE TABLE BOX (
	BOX_ID				INTEGER NOT NULL,
    NAME				VARCHAR(50),
    BESCHREIBUNG		VARCHAR(50),
    PREIS				DECIMAL(10,2),
    BESTELLNR			INTEGER,
    ZUTAT_ID			INTEGER,
    PRIMARY KEY (BOX_ID),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (ZUTAT_ID) REFERENCES ZUTAT (ZUTAT_ID)
);

CREATE TABLE REZEPT (
	REZEPT_ID 			INTEGER NOT NULL,
    NAME 				VARCHAR(50),
    ANLEITUNG			VARCHAR(500),
    MENGE				INTEGER,
    PRIMARY KEY (REZEPT_ID)
);

CREATE TABLE REZEPT_ZUTAT (
	MENGE			INTEGER,
    ZUTAT_ID		INTEGER,
    REZEPT_ID		INTEGER,
    PRIMARY KEY (REZEPT_ID, ZUTAT_ID),
    FOREIGN KEY (ZUTAT_ID) REFERENCES ZUTAT (ZUTAT_ID),
    FOREIGN KEY (REZEPT_ID) REFERENCES REZEPT (REZEPT_ID)
);

