on: 
  push: 
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
name: 🚀Push Notification
jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Webhook
      uses: tsickert/discord-webhook@v5.3.0
      with: 
        webhook-url: https://discord.com/api/webhooks/1201850371715112970/ruyvffCQ5K6q4OId-pAdVgfQTrVKi9YPfJDn5wTF7JThncDXK32pGGDbOmWFqsuZR-ky
        content: "@<564842830619475979> @<239429927542325258> @<691226066580144148> New Push on [Github](<https://github.com/JonasRingeis/LF5-Kraut-Und-Rueben-Database/>)\n\nCommit: ${{ github.event.head_commit.message }}"    
